version: '3'
services:
  react-app:
    build: 
      context: ./
      dockerfile: dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
  react-app-tests:
    build: 
      context: ./
      dockerfile: dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    command: ["npm", "run", "test"]